apps/Empresas/urls.py
from django.urls import path
from .views import *
app_name = 'empresas'
urlpatterns = [
    path('empresas/', EmpresaListView.as_view(), name='empresas_lista'),
    path('editar/<int:pk>/', editar_empresa, name="editar"),
    path('eliminar/<int:pk>/', eliminar_empresa, name="eliminar"),
    path("agregar/", agregar_empresa, name="agregar"),
]

apps/PC/urls.py
from django.urls import path
from .views import PCView,DetallePCView, AgregarHistorialView, EliminarEquipoView, AgregarEquipoView
app_name = 'pc'
urlpatterns = [
    path('pc/', PCView.as_view(), name='pc_list'),
    path('pc/<str:serial>/', DetallePCView.as_view(), name='detalle_pc'),
    path('detalle/<str:serial>/agregar_historial/', AgregarHistorialView.as_view(), name='agregar_historial'),
    path('detalle/<str:serial>/eliminar/', EliminarEquipoView.as_view(), name='eliminar_equipo'),
    path('agregar_equipo/', AgregarEquipoView.as_view(), name='agregar_equipo'),

]

apps/User/urls.py
from django.urls import path, re_path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    re_path('logout/', views.logout_view, name='logout'),
    path('', views.bienvenida_view, name='home')

]

core/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('apps.User.urls')),       # Se mantiene en raíz
    path('', include('apps.PC.urls')),      # Añade prefijo para esta app
    path('', include('apps.Empresas.urls')),  # Añade prefijo para esta app
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/canvas.html
{% load static %}

    {% block head %}
    <style>
        .ccanvas {
            background-color: transparent; 
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
            border-bottom: none !important;
        }
    </style>
    <link rel="stylesheet" href="{% static 'canvas.css' %}">
    {% endblock head %}

<!-- Encabezado con botón e icono de usuario alineados -->
<div class="d-flex justify-content-between align-items-center px-3 py-2 ccanvas">
    <!-- Botón menú (izquierda) -->
    <button class="btn btn-menu" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasExample">
        <i class="bi bi-text-indent-left fs-4"></i>
    </button>

    <!-- Menú de usuario (derecha) -->
    <div>
        <a href="{% url 'user:logout' %}" class="btn btn-outline-danger">Cerrar sesión</a>
    </div>
</div>


<!-- Offcanvas lateral -->
<div class="offcanvas offcanvas-start ccanvas" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel" style="background-color: transparent; backdrop-filter: blur(10px);">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel" style="color: white !important; font-size: 2.2rem;">
            <strong>{{ request.user.first_name }} {{ request.user.last_name }}</strong>
        </h5>
        <button type="button" class="btn-close" style="filter: brightness(0) invert(1);" data-bs-dismiss="offcanvas" aria-label="Cerrar"></button>

    </div>
    
    <div class="offcanvas-body">
        <ul class="nav nav-pills flex-column mb-auto">
            <li>
                <a href="{% url 'user:home' %}" class="custom-nav-link">
                    <i class="bi bi-house"></i> Página principal
                </a>
                <a href="{% url 'pc:pc_list' %}" class="custom-nav-link">
                    <i class="bi bi-laptop"></i> Equipos de computo
                </a>
                <a href="{% url 'empresas:empresas_lista' %}" class="custom-nav-link">
                    <i class="bi bi-buildings"></i> Empresas
                </a>
            </li>
        </ul>
    </div>
</div>